name: Download
inputs:
  ArtifactName:
    required: true
  PyVersionLatest:
    required: true
  PkgRootFolder:
    required: true
runs:
  using: composite
  steps:
  - name: Download ${{inputs.ArtifactName}}
    uses: actions/download-artifact@v4.1.0
    with:
      name: "${{inputs.ArtifactName}}"
      path: "${{runner.temp}}/${{inputs.ArtifactName}}"
  - name: Use Python ${{inputs.PyVersionLatest}}
    uses: actions/setup-python@v5.0.0
    with:
      python-version: "${{inputs.PyVersionLatest}}"
      architecture: x64
  - name: Environment Setup
    run: python -m pip install --upgrade --requirement requirements_test.txt
    working-directory: "${{inputs.PkgRootFolder}}"
    shell: bash
  - name: List files
    run: Get-ChildItem -Path .\ -Recurse -Force
    working-directory: "${{ runner.temp }}"
    shell: pwsh
  - name: Unit and Integration Tests
    env:
      TEMP: "${{ runner.temp }}"
      TMP: "${{ runner.temp }}"
      TESTRESULTSPATH: "${{ runner.temp }}"
      COVRESULTSPATH: "${{ runner.temp }}\\cov.xml"
    run: tox --installpkg ${{ runner.temp }}/${{inputs.ArtifactName}}/* -vv -r -s true
    shell: bash
    working-directory: "${{inputs.PkgRootFolder}}"